### ISSUE TITLE
socket connection is not connected although pusher:connection_established event was fired

### ISSUE THREAD

**Issue by thanhn08** [pusher/pusher-websocket-swift#51] opened 2016-06-02 09:49 UTC
Hi,

I have a problem with Pusher that I need support. Whenever I use the app, then press power button to turn screen off, the socket connection will be closed. When I turn on again, I listen to connectionStateDelegate to make connection again. However, it cannot auto re-subscribe to existing channels because socket connection is not connected. Please check the code below:

```
    private func handleConnectionEstablishedEvent(json: PusherEventJSON) {
        if let data = json["data"] as? String {
            if let connectionData = getPusherEventJSONFromString(data), socketId = connectionData["socket_id"] as? String {
                updateConnectionState(.Connected)
                self.socketId = socketId

                print("socket: \(socketId) - connected: \(self.socket.isConnected)") // this shows connected: false

                for (_, channel) in self.channels.channels {
                    if !channel.subscribed {
                        if !self.authorize(channel) {
                            print("Unable to subscribe to channel: \(channel.name)")
                        }
                    }
                }
            }
        }
    }
```

As you can see, the log in the middle of the function is what I used to debug, it prints out connected: false. 
According to my debug, this code did enter the `authorize(channel)` but socket is not connected so it cannot call to pusher server (no debug log on pusher server as well).

Sometime this works fine, because socket can make connection before this method is called. But most of the time it won't work.... I don't know why `handleConnectionEstablishedEvent` is called when event `pusher:connection_established` is fired, but still socket connection is not ready. Could this be pusher server problem or the WebSocket library problem (Starscream)?

In the meantime, I will switch back to libPusher (ObjC library) which didn't have this problem in my other apps. But libPusher is kinda outdated so I would like to use this library more. Hope you guys can have this resolved soon. Thank you.

**Comment by hamchapman** [comment] 2016-06-02 12:45
There might be a bug here but I just want to make a few things clear about how the library should be working by default.

If you haven't explicitly set `autoReconnect` to false then upon disconnection all channels will have their `subscribed` property set to false.

Upon reconnection, the client will receive a `pusher:connection_established` event which will then re-establish subscriptions to channels that were previously subscribed to, prior to the disconnection. 

As I say, this is the default behaviour. You don't need to handle calling `connect` again or anything like that.

If a `pusher:connection_established` event is received then the socket connection is definitely open. It can't receive it otherwise.

It looks like there could be a scenario where the `pusher:connection_established` event is received over an open socket and the socket is then _immediately_ closed, before the handling of the connection established event has completed. However, this seems incredibly unlikely. If you're able to reliably reproduce this or provide steps for doing so then please could you provide a sample project or a list of steps to reproduce?

**Comment by hamchapman** [comment] 2016-06-16 09:23
@thanhn08 have you encountered this problem again?

If so, could you try with PusherSwift 1.0.0 (the latest release) to see if it's still occurring?

**Comment by hamchapman** [comment] 2016-07-07 10:54
@thanhn08 any updates or can I close the issue?

**Comment by thanhn08** [comment] 2016-07-07 10:55
Sorry i have been too swamped. I will check this soon tonight or tomorrow.

**Comment by hamchapman** [comment] 2016-09-20 22:11
Hi @thanhn08, if this is still relevant to you, please could you try using PusherSwift 3.1.0 (the latest release) to see if it's still occurring?

**Comment by hamchapman** [comment] 2016-09-28 14:20
Closing as stale - if this is still occurring then we can reopen 👍

**Comment by CataD256** [comment] 2016-11-10 00:02
I can reproduce the same issue on 2.0.1. Could you include a fix for it or give a hint where I should look?

**Comment by CataD256** [comment] 2016-11-10 00:53
You are processing the first message to get the code based on which you set the value for connected, but when that message is processed, you also call the delegate method for received message. Thus you end up calling the delegate method for a message handling before actually updating the socket connection.

**Comment by hamchapman** [comment] 2016-11-10 10:27
@CataD256 I'm not sure I understand what you're saying. The when you say "delegate method", which delegate method do you mean? Do you mean the `debugLog` method? If so, that shouldn't have any impact as it's just there for debugging. It's not doing anything to change state internally. If you're referring to a different delegate method, please let me know which one 🙂

I'm also not quite sure what you mean by this: 

> You are processing the first message to get the code based on which you set the value for connected

The only thing I've just seen is that in this line: https://github.com/pusher/pusher-websocket-swift/blob/fe6563ba9ff08b755a8ff4b4c2323b177fdfdb7b/Source/PusherWebsocketDelegate.swift#L35 I might need to include the case where the connection state is already marked as disconnected. You could try testing that to see if that fixes it for you?

**Comment by CataD256** [comment] 2016-11-10 10:39
I traced the code and got to the following scenario:

**Comment by hamchapman** [comment] 2016-11-10 14:08
I can confirm that yes, `websocketDidReceiveMessage` is called before `websocketDidConnect` is called. That's to be expected though, as the `pusher:connection_established` message is sent on connection. That's also what this library (PusherSwift) uses to determine when a connection is established and therefore when to set the `connectionState` property to `.connected`.

As you can see here, the `websocketDidConnect` delegate function is not used at all: https://github.com/pusher/pusher-websocket-swift/blob/master/Source/PusherWebsocketDelegate.swift#L106

I guess my real question is, what's the problem with what currently happens?

I've tried (using the included iOS Example app) calling `disconnect()` and `connect()` over and over again on the `Pusher` object and the channels always seem to resubscribe. Is that where your problem is occurring - lack of resubscription?

**Comment by CataD256** [comment] 2016-11-10 14:18
This is the way I use the library.

```Swift
    internal func connectIfNeeded() {
        if pusher.connection.connectionState == .Disconnected {
            self.pusher.connect()
        }
    }
    
    internal func subscribeToChannel(listId: Int, delegate: PusherManagerProtocol) {
        connectIfNeeded()
        let channelName = "channel_list_\(listId)"
        self.subscribedChannel.append(channelName)
        let channel = self.pusher.subscribe(channelName)
        
        for event in events {
            channel.bind(event.rawValue, callback: { (data) in
                delegate.onEventReceived(event, data: data)
            })
            self.subscribedChannelEvents.append(event)
        }
    }

    internal func unsubscribe(completion: (() -> ())? = nil) {
        self.pusher.unbindAll()
        subscribedChannelEvents.removeAll()
        
        for item in self.subscribedChannel {
            self.pusher.unsubscribe(item)
        }
        subscribedChannel.removeAll()
        
        self.pusher.disconnect()
        
        if completion != nil {
            completion!()
        }
    }
```

I alternate calling "subscribeToChannel" and then "unsubscribe". Would this, in your opinion lead to som inconsistency, or could it make a channel end up not being able to subscribe?

**Comment by hamchapman** [comment] 2016-11-10 14:27
It obviously depends a bit on the context of your specific use case but for the general case I've got a few notes about how you're interacting with the library.

If you want a client to stop receiving events from Pusher, the only thing you really need to do is to call `self.pusher.disconnect()`. That should be enough. That will leave all event handlers tied to any channels that were subscribed to when `disconnect` was called, and will keep track of all the channels themselves that were subscribed to. 

That means that if you then want to reconnect, all you need to do is call `self.pusher.connect()`. You don't have to worry about calling `subscribe`, or worry about calling `unsubscribe` or `unbind(All)` when disconnecting in the first place.

If you don't just want to disconnect and instead you want to have a "fresh" state when someone does something that calls the `internal func unsubscribe(...)` in your code above, then I'd recommend just calling `self.pusher.disconnect()` and then when someone wants to reconnect with no channel subscriptions etc, then just assign a new `Pusher` client object to `self.pusher`, i.e. `self.pusher = Pusher("YOUR_APP_KEY", options: YourPusherClientOptions)`.

**Comment by CataD256** [comment] 2016-11-10 14:35
I'll try with reinstantiating my pusher object. Will let you know of the outcome :)

**Comment by hamchapman** [comment] 2016-11-11 10:46
@CataD256 Any luck?

**Comment by CataD256** [comment] 2016-11-11 10:50
Hey @hamchapman! I tried the recreating the pusher object every time I want to subscribe to a channel, but I can still randomly reproduce the issue. I could give you the state of the connection and channels when that happens. Trying to call reconnect does not seem to help when I get in that state.

**Comment by hamchapman** [comment] 2016-11-11 13:20
Interesting. And yeah, having the state of the connection and the channels when the issue occurs would definitely be handy!

Also, just to be clear, is the issue that subscriptions aren't reestablished when you then call `connect` again?

**Comment by CataD256** [comment] 2016-11-11 13:46
It happens on the first try also, not necessarily on re-subscription.

**Comment by hamchapman** [comment] 2016-11-11 14:00
Subscriptions sometimes don't work even when just calling `connect()` for the first time?

Would you be able to create a project that contains code that will recreate the issue? That would be a massive help with debugging this. Thanks!

**Comment by hamchapman** [comment] 2016-11-14 11:09
#108 should fix this issue. I'll be releasing a version 4.0.2 today :

**Closed** 2016-11-14 11:09 UTC
Labels: investigate
