### ISSUE TITLE
Obj-C Starscream.WSError. error 1 (AuthRequestBuilder not being called)

### ISSUE THREAD

**Issue by Mootook** [pusher/pusher-websocket-swift#279] opened 2020-08-14 18:26 UTC
I had been using libPusher for iOS pusher handling, but my team and I are recently migrating some of that code over to tvOS, which means we've had to adopt this library instead.

We use a custom auth endpoint, supplied with a header token for channel authorization, and I've been trying to set it up. Either because of my misunderstanding of the configuration flow or something else, I've continually run into connection errors when attempting subscriptions (private channels). I'm also unable to get logs or breakpoints at the `requestForSocketID:(NSString *)socketId channelName:(NSString *)channelName;` protocol implementation from `AuthRequestBuilderProtocol`.

I've created a pusher manager class as a singleton with a strong reference to the `Pusher` client object as well as assigned the singleton as the client's connection delegate. I've created a custom AuthRequestBuilder as the docs suggested but am unable to diagnose the connection issue.

    // PusherManager.m
    #import "PusherManager.h"
    #import "PusherAuthRequestBuilder.h"

    @interface PusherManager ()
    @end

    @implementation PusherManager

    +(id)sharedInstance {
        static PusherManager *sharedInstance = nil;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            sharedInstance = [[self alloc] init];
            NSString *cluster = @"CLUSTER";
            NSString *pusherKey = @"SECRET";
            OCAuthMethod *authRequestBuilder =
                [[OCAuthMethod alloc] initWithAuthRequestBuilder:[[PusherAuthRequestBuilder alloc] init]];
            OCPusherHost *host = [[OCPusherHost alloc] initWithHost:cluster];
            PusherClientOptions *options =
                [[PusherClientOptions alloc] initWithOcAuthMethod:authRequestBuilder
                                                    autoReconnect:YES
                                                           ocHost:host
                                                             port:nil
                                                           useTLS:YES
                                                  activityTimeout:nil];
            sharedInstance.client = [[Pusher alloc] initWithAppKey:pusherKey options:options];
            sharedInstance.client.connection.delegate = sharedInstance;
            [sharedInstance.client connect];
        });
        return sharedInstance;
    }

    - (void)debugLogWithMessage:(NSString *)message {
        NSLog(@"%@ WITH CONNECTION STATE %ld", message, self.client.connection.connectionState);
        // [PUSHER DEBUG] Waiting 1.0 seconds before attempting to reconnect (attempt 2) WITH CONNECTION STATE 4
    }

    // PusherAuthRequestBuilder.m
    #import "PusherAuthRequestBuilder.h"
    @implementation PusherAuthRequestBuilder
    -(NSURLRequest*)requestForSocketID:(NSString *)socketID channelName:(NSString *)channelName {
        NSString *authUrl = @"MY AUTH URL";
        NSURLRequest *request = [[NSURLRequest alloc] initWithURL:[[NSURL alloc] initWithString:authUrl]];
        NSMutableURLRequest *mutableRequest = [[NSMutableURLRequest alloc] initWithURL:[[NSURL alloc] initWithString:authUrl]];
        NSString *dataString = [NSString stringWithFormat:@"socket_id=%@channel_name=%@", socketID, channelName];
        NSData *data = [dataString dataUsingEncoding:NSUTF8StringEncoding];
        mutableRequest.HTTPBody = data;
        mutableRequest.HTTPMethod = @"POST";
        NSString *token = @"MYTOKEN"
        [mutableRequest addValue:[NSString stringWithFormat:@"Bearer %@", token] forHTTPHeaderField:@"Authorization"];
        request = [mutableRequest copy];
    
        return request;
    }
    @end

### Expected behavior

Connection occurs or passes through `requestForSocketId` protocol. If that fails allow more robust logging from `debugLogWithMessage` PusherDelegate method. 

Any help would greatly be appreciated. Thank you.

**Comment by danielrbrowne** [comment] 2020-08-18 13:21
@Mootook Have you confirmed if the `client` property of your `PusherManager.sharedInstance` is non-nil at the point where the private channel subscription is attempted? I can't obviously see how it wouldn't be being retained from your code listing, but I'm asking as another user (albeit writing Swift) had a similar issue (i.e. where the `requestForSocketId` method wasn't being called).

This turned out to be because their `Pusher` instance had become deallocated, see: https://github.com/pusher/pusher-websocket-swift/issues/274#issuecomment-664191375

**Comment by Mootook** [comment] 2020-08-18 17:00
@danielrbrowne, The client property is not becoming nil. I've done a similar setup with it being a singleton class with other libraries.
Also, I am getting ocassional logs from `debugLogWithMessage:(NSString*)message` about the client's connection state after the any subscription flow is run to initialize the singleton. Assuming this is from the `reconnect` attempt `[PUSHER DEBUG] Waiting 64.0 seconds before attempting to reconnect (attempt 9) WITH CONNECTION STATE 4`

I did see the example/issue you posted, and just for testing sake I did setup a minified flow on a view controller, but I got the same outcome.

**Comment by danielrbrowne** [comment] 2021-01-11 17:02
@Mootook I was wondering if you're still seeing this issue in the latest v9.1.1 release? (There's been several improvements over the v8.0.0 release to reconnection logic and error-reporting, as well as the Starscream WebSocket client library dependency being removed).

**Comment by Mootook** [comment] 2021-01-11 23:53
@danielrbrowne Hello, sorry but I no longer have the project or means to test this at this time.

**Comment by danielrbrowne** [comment] 2021-01-11 23:57
Ok thanks for the feedback. Given all the recent changes (which are likely to have made this issue redundant) I'll close the issue for now. Feel free to reopen it if this changes.

**Closed** 2021-01-11 23:58 UTC
Labels: bug
