### ISSUE TITLE
No reconnection after error on version 9.0.0 only

### ISSUE THREAD

**Issue by benjamincombes** [pusher/pusher-websocket-swift#310] opened 2020-11-12 16:33 UTC
### Steps to reproduce

1. Open the app using the Pusher SDK
2. Wait until a network error occurs (examples "Error (code: 1): The operation couldn’t be completed. (Starscream.WSError error 1." or "Error (code: 0): The operation couldn’t be completed. (Network.NWError error 0.)")

### Expected behavior

The connection should recover, and app should be able to receive new messages again

### Actual behavior

The connection never recovers, you won't receive any message after that

### Any improvements you suggest

This was not the case on version 8, this is the case only with version 9 of the SDK, we had to revert to version 8 just before submitting the app, because it was unusable on all our testers with a medium-quality internet connection. Just rolling back to version 8 (and just that) fixed the issue.

**Comment by danielrbrowne** [comment] 2020-11-12 16:55
Were you simulating network connectivity issues in some way? I'd like to be able to reproduce your testing scenario to compare the v8.0.0 and v9.0.0 behaviour

**Comment by benjamincombes** [comment] 2020-11-12 17:01
No, this was with real users only, not with simulating network issues. I sent the app to test to members of our team hoping this new version would solve errors we see, and 3 of them (on 5 users) were stuck because no messages would appear anymore after using the app a few minutes (or less). 
With version 8, when an error occurred (like described here: https://github.com/pusher/pusher-websocket-swift/issues/311), it would be "only" a few messages lost, and the connection would be restored. But with version 9, once one of this problem occurs, no messages are received ever again. For one of them, it was a 100% reproduction rate after 30 seconds of using the app.

**Comment by zinlinphyo** [comment] 2020-12-12 18:09
I have the same issue when I connect with the host with custom URL. Still not working.

`Websocket received error. Error (code: 0): The operation couldn’t be completed. (Network.NWError error 0.)`

**Comment by benjamincombes** [comment] 2020-12-14 08:26
Hi, same from me, we made tests with the new version and had to rollback immediately

**Comment by danielrbrowne** [comment] 2020-12-14 09:03
@zinlinphyo @benjamincombes I'm a little unclear on things - are you both saying you're still having issues with the most recent v9.1.0?

That version contains a number of improvements to the reconnection logic as compared to 9.0.0, largely based on the previous discussion in this issue.

**Comment by danielrbrowne** [comment] 2020-12-14 09:23
In fact, at least in @zinlinphyo I can confirm you aren't using the latest v9.1.0 as I changed the error-logging signature to provide more context on errors as part of the reconnection improvements I mentioned, and your comment references the old error-logging signature format present in 9.0.0 and below. ([see here](https://github.com/pusher/pusher-websocket-swift/pull/313/commits/67f6e78cc8ea0ff69938c71c58f4f4929ea7f1c3#diff-43e4feb59ad4edcca3e759ecec12979c9d580c35a6b9e695a1fab0f169dbf980R238)).

**Comment by benjamincombes** [comment] 2020-12-14 09:51
Hi @danielrbrowne, yes, with the new 9.1 version unfortunately. When it got released, I pushed a new build for my team to test it (I reverted to version 8.0.0, as 9.0.0 didn't work well). But before I even had time to tell them, 2 of them wrote me to know what happened with the app, as they had many many problems and undelivered messages, while the previous version (8.0.0) worked well.

**Comment by danielrbrowne** [comment] 2020-12-14 09:56
@benjamincombes Can you please give me some examples of the kind of connection errors you are seeing from the SDK, and (if possible) the exact scenarios in which they are appearing and then presumably where you're not seeing the SDK reconnect after receiving the error(s).

**Comment by danielrbrowne** [comment] 2020-12-14 17:14
@benjamincombes @zinlinphyo I believe that [this PR](https://github.com/pusher/NWWebSocket/pull/24) that I opened should resolve the race condition preventing reconnection attempts from working sometimes. One of my colleagues will review it but I welcome any feedback you both have.

Assuming no issues, it will be shipped as a minor update (likely v9.2.1) as soon as possible after it passes code review.

**Comment by benjamincombes** [comment] 2020-12-15 10:15
Thanks @danielrbrowne, I will try it as soon as possible, I'm working on getting my user's logs to have more details for you too, thanks

**Comment by danielrbrowne** [comment] 2020-12-15 11:21
@benjamincombes @zinlinphyo The fix for this race condition is available in v9.1.1 which I've just released.

With an example app, I tested reconnections in the following circumstances (and compared the SDK behaviour to v9.1.0 to confirm reconnections were successful):
- Moving the app to the background, and then using another app before returning the example app to the foreground.
- Turning Airplane Mode on and then off to simulate a loss of network connection.

Please let me know if this has improved things for you. If so, I will then close this issue.

**Comment by benjamincombes** [comment] 2020-12-15 13:54
@danielrbrowne OK I'll let you know as soon as possible. 
If you want advanced tests on your side too, "Settings -> Developer Settings -> Network Link Conditioner -> Very Bad Network" allowed me to have great testing conditions of a bad network (even if I didn't get all errors one of my users got).

**Comment by danielrbrowne** [comment] 2020-12-15 14:25
@benjamincombes Thanks for reminding about the Network Link Conditioner - I can confirm that even when using that preset, I see the reconnections happening successfully. I look forward to your feedback on whether v9.1.1 resolves the issue for you.

**Comment by danielrbrowne** [comment] 2020-12-18 12:42
@benjamincombes @zinlinphyo Can I assume the latest 9.1.1 release resolved this issue for your teams? I will close it if I've not heard back by 5:30pm GMT today, but please let me know if you have any issues with this in the future.

**Comment by nicoreese** [comment] 2020-12-21 12:27
Hi!

I am having a similar issue. 

The connection status is changing from disconnected to connecting before receiving the following error:

On 9.0.0 the error is
`[PUSHER DEBUG] Websocket received error. Error (code: 0): The operation couldn’t be completed. (Network.NWError error 0.)`
while on the latest 9.1.1 it's
`[PUSHER DEBUG] Websocket received error. Error: POSIXErrorCode: Software caused connection abort`

I am using a custom host with this simple example. I use the same method in the Javascript SDK in React and it works fine and it's also connecting using webecho.org's tester.

 ```
let options = PusherClientOptions(
            host: .host("DOMAIN"),
            port: 6001
        )
        
        pusher = Pusher(key: "XXXXX", options: options)
        pusher.connection.delegate = self
        pusher.connect()
```

**Comment by danielrbrowne** [comment] 2020-12-21 12:44
@nicoreese 

I'm sorry you're having an issue connecting to a custom server. However since it's not specifically to do with reconnection after a loss of connection could you open a new issue instead please? (The root cause is likely not related based on the error message).

Please include as many specifics as possible so that I can try to reproduce. From what I've read it's fine on v9.1,1 when connecting to a test server, but NOT when connecting to your custom host? If so please clarify that and any other details in the new ticket.

**Closed** 2020-12-21 12:45 UTC
Labels: bug
