### ISSUE TITLE
crash in TaskQueue

### ISSUE THREAD

**Issue by kkaliher** [pusher/pusher-websocket-swift#96] opened 2016-10-05 20:00 UTC
When running in the simulator only (Xcode 8, Sierra), we often see a crash in TaskQueue after leaving the app running for some time, maybe 10 minutes or so.  It looks like line 129 can enter an infinite loop.

I tried commenting out line 115, if task == nil, and that seemed to help things, but not sure if that is the best approach.

**Comment by hamchapman** [comment] 2016-10-06 15:29
Thanks for the report - do you have an example that reproduces the issue? Or at least the minimum code needed to reproduce it. 

I've tried to recreate it locally but unsuccessfully thus far.

Thanks!

**Comment by kkaliher** [comment] 2016-10-07 20:01
hey Ham, thanks for the response.  
We reverted this line 115 comment out as that broke push notifications.  
The best approach to the issue here was to just not setup push or subscribe to interests if running on simulator.

**Comment by esetnik** [comment] 2016-10-08 20:05
I'm seeing the same crash. I think this should be reopened. The library should be able to run without modifications on the simulator. Thanks for the workaround @kkaliher.

**Comment by hamchapman** [comment] 2016-10-10 08:21
Agreed - thanks for the notes guys.

If anyone has some code or a project that exhibits the bug (plus info about which version of Xcode and iOS version + plus device you're using) that would be awesome as I'm still struggling to reproduce it locally.

Thanks!

**Comment by esetnik** [comment] 2016-10-14 15:21
@hamchapman I have narrowed down the issue. It occurs when you subscribe to an interest in the simulator when the push notifications cannot be registered. I have created a sample project that reproduces the issue but it contains push notification keys so I'd rather share it with your team privately. If you can provide an email address to send it I'll forward it along.

**Comment by esetnik** [comment] 2016-10-14 15:28
By the way this issue is not limited to the simulator. If a user denies your notification permissions and you still attempt to subscribe to an interest the app will crash after ~5min.

**Comment by hamchapman** [comment] 2016-10-14 15:43
That would be great! My email is my GitHub username @ gmail (.com). Thanks!

**Comment by hamchapman** [comment] 2016-10-18 03:45
I've taken a look at the project and had a play with it and have written up a small fix which I'm still doing some testing on locally just to be sure.

I should have a fix for this ready for review soon!

**Comment by hamchapman** [comment] 2016-10-18 16:22
This pull request should fix this issue https://github.com/pusher/pusher-websocket-swift/pull/100

**Comment by hamchapman** [comment] 2016-10-21 13:28
@esetnik, @kkaliher have either of you had a chance to test the branch with the proposed fix on it?

**Comment by esetnik** [comment] 2016-10-25 01:27
I have tested the branch containing the fix and I haven't found any crashing issues

**Comment by esetnik** [comment] 2016-10-25 18:16
I tried out your fix and haven't had any issues since.

On Fri, Oct 21, 2016 at 9:28 AM Hamilton Chapman

<
mailto:Hamilton Chapman <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/esetnik
,
https://github.com/kkaliher
have either of you had a chance to test the branch with the proposed fix on it?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/pusher/pusher-websocket-swift/issues/96#issuecomment-255376492
, or

**Comment by esetnik** [comment] 2016-11-07 19:13
Can this get merged in?

**Comment by hamchapman** [comment] 2016-11-07 19:41
I was just working on this today. It should be merged in tomorrow, along with some changes to how the delegates are implemented on the connection and top level Pusher objects.

**Comment by hamchapman** [comment] 2016-11-09 13:04
Took longer than expected to get to this - will be releasing the new version today.

**Closed** 2016-11-09 15:19 UTC
Labels: bug, fix-proposed

**Comment by hamchapman** [comment] 2016-11-09 18:02
Just pushed a new version (4.0.0). A few breaking changes around the `PusherDelegate` and `PusherConnectionDelegate` but shouldn't be too big a deal.
