### ISSUE TITLE
disconnecting while entering the background

### ISSUE THREAD

**Issue by mrlantan** [pusher/pusher-websocket-swift#43] opened 2016-05-06 09:30 UTC
I recently found, that when I hit the power button, the device unsubscribes from the channel and when the app comes back to foreground it doesn't connect again.
I decided to do it manually in connectionChange delegate method in the way
```objective-c
func connectionChange(old: ConnectionState, new: ConnectionState) {
        switch new {
        case .Disconnected:
                self.pusher.connect()
        }
        ...
}
```

This didn't work because in your
 ```objective-c
private func updateConnectionState(newState: ConnectionState) {
        self.stateChangeDelegate?.connectionChange(self.connectionState, new: newState)
        self.connectionState = newState
}
```
you firstly call the delegate method and then change the state. So when i tried to call
```objective-c
self.pusher.connect()
```

```objective-c
public func connect() {
        if self.connectionState == .Connected {
            return
        } else {
            updateConnectionState(.Connecting)
            self.socket.connect()
            if let reconnect = self.options.autoReconnect where reconnect {
                _ = try? reachability?.startNotifier()
            }
        }
    }
```

this func returned because current state was .Connected

I would suggest swapping lines in updateConnectionState method  creating a variable to store the self.connectionState value and pass it then to the delegate method parameters. So it may look like :
```objective-c
private func updateConnectionState(newState: ConnectionState) {
    let oldConnectionState = self.connectionState
    self.connectionState = newState   
    self.stateChangeDelegate?.connectionChange(oldConnectionState, new: newState)
}
```

**Comment by hamchapman** [comment] 2016-05-06 09:37
Interesting - was it reconnecting successfully but then not resubscribing to any channels you had been subscribed to?

And that's a very valid point in terms of swapping the order of the lines - do you want to make a PR for it?

**Comment by mrlantan** [comment] 2016-05-06 10:12
So here is my flow:
1. I run the app and pusher connects and subscribes to a channel.
On the dashboard.pusher.com I get these lines
![image](https://cloud.githubusercontent.com/assets/8770111/15070051/923110ba-138a-11e6-97cf-78fe0fcbdb43.png)
2. I hit the power button on my IPhone and immediately get this line
![image](https://cloud.githubusercontent.com/assets/8770111/15070068/adbe3858-138a-11e6-99b3-83b88946993f.png)
3. I unlock the iphone, bring the app back to foreground and when I try to send pushes, callbacks are not called.

I worked around an issue that I described in the post by calling connect in this way
```objc
case .Disconnected:
            dispatch_async(dispatch_get_main_queue(), {
                self.pusher.connect()
            })
```

with this modification, after app comes back to foreground, pusher connects again and I can receive pushes again.
Here is the line i get on dashboard.pusher.com 
![image](https://cloud.githubusercontent.com/assets/8770111/15070173/5d6ff6b0-138b-11e6-89f5-1a04d26175c4.png)

Dashboard doesn't send the line about subscribing again

Hope now it's more clear :)

I do not exactly understand, what does it mean to make PR off this.

**Comment by hamchapman** [comment] 2016-05-09 16:04
I've tried to recreate this locally and I also don't get the subscribe showing up in the debug console again. However, I don't think this is a problem, at least it wasn't for me, as there also wasn't an unsubscribe. If there's an unsubscribe then obviously you need the subscribe again, but in my case, when I reconnected (turned wifi back on) then I started to be able to receive messages again.

Do you have an example app I can download where you're experiencing the problem?

**Comment by hamchapman** [comment] 2016-05-17 13:57
Any updates @mrlantan?

**Comment by hamchapman** [comment] 2016-06-02 08:51
Closing for now under the assumption that the problem isn't occurring anymore. Let me know if that's not the case and we can reopen the issue

**Closed by hamchapman** 2016-06-02 08:51 UTC
