### ISSUE TITLE
Pusher doesn't receive messages after a network change or has an network error

### ISSUE THREAD

**Issue by quoctc** [pusher/pusher-websocket-swift#170] opened 2018-02-01 04:31 UTC
### What is the issue?
I got an issue same as this topic:
https://github.com/pusher/pusher-js/issues/223
Do you fix for swift client version?
It's hard to reproduce the issue, But, at the last time I got the error, I debugged and saw the pusher status is connected, the network was OK, but before a moment when that issue happens, the network was not stable. 
... 

### Is it a crash report? Submit stack traces or anything that you think would help
This is the image that shown my client was Disconnected > Vacated > ... After that the issues that I told you happen until I'm fore to reconnect and subscribe channel again.
<img width="702" alt="screen shot 2018-01-24 at 10 23 27 pm" src="https://user-images.githubusercontent.com/900704/35661187-1b4451c0-0743-11e8-91d9-c7354e04429e.png">

For more information:
Can you see the events being triggered in the Pusher Debug Console? YES
Are your users connected when you expect them to receive events? To check this you should monitor connection state within the client application. YES
...

### Any improvements you suggest

...

---- 

CC @pusher/mobile

**Comment by hamchapman** [comment] 2018-02-01 17:15
@quoctc I've just tried to recreate this by disabling wifi and then turning it back on repeatedly but I can't seem to recreate it.

Just to be clear - the series of events that you're experiencing is:

* successfully connected and subscribed to a channel that is receiving events
* network event leads to disconnection
* reconnection occurs
* client seems to have reconnected but channel isn't receiving new events

Is that correct?

**Comment by quoctc** [comment] 2018-02-02 00:25
Yes, I debugged and my app seem to never call to these function:
- internal func handleEvent(name: String, data: String, channelName: String?) 
- internal func handleErrorEvent(name: String, data: [String: AnyObject])

**Comment by roshanr95** [comment] 2018-02-05 14:00
I think I ran into the same issue.
Steps to reproduce:
1. Connect to Pusher. Events are received as usual.
2. Turn off Wifi for ~5 min.
3. Turn on Wifi.

What I can observe is that there is a Disconnection message in the web console once Wifi is turned on, but in the app, `pusher.connection.connectionState` still returns `connected` and `pusher.connection.socketId` returns the disconnected(as seen in the web console) socket id.

@hamchapman It sometimes works fine if Wifi is turned off for less than 2-3 min - it auto reconnects and receives events again. If you didn't disable Wifi for long, this is why you weren't able to reproduce it.

I've also added
```
        pusher.connection.reconnectAttemptsMax = nil
        pusher.connection.maxReconnectGapInSeconds = 60
```
but it doesn't change anything.

I've also added a listener on `changedConnectionState`, but the only time it fires is during the initial connection setup - it goes from `connecting` to `connected`.

From what I can gather, there may be an error in state management which doesn't record the connection as disconnected. Or maybe there's some limit that is getting hit somewhere when disconnected for too long and Pusher stops retrying.

**Comment by quoctc** [comment] 2018-02-07 02:37
Oh thank you @roshanr95, I could do a quick fix on my app. After re-connect, I will call to re-subscribe channels again to avoid it. Hope you can fix it on next release version. Thank!

**Comment by borulday** [comment] 2018-03-19 11:23
Hi @hamchapman  

To re-create the issue, 
- Connect internet via VPN,
- Close VPN and open it as quick as possible. Just try to simulate the heartbeat. (I'm using VPN Unlimited and when I try to disconnect it from menu bar icon, it already behaves like that. =) )

PS: VPN isn't necessary but easy to trigger this issue via VPN.

Thanks!

**Comment by hamchapman** [comment] 2018-03-23 16:06
You should be able to try the `cleanup-crash-fix` branch (associated PR here: https://github.com/pusher/pusher-websocket-swift/pull/178)

This should have fixed this problem. 

Let me know if you're able to and what results you see 👍  I'm hoping to merge that PR and release 6.0.0 on Monday if all goes well.

**Comment by borulday** [comment] 2018-03-24 11:37
Hi again @hamchapman Thanks for the information. I tried the `cleanup-crash-fix` branch for the same VPN scenario but sadly nothing changes. Here are the `debugLogs` function results. Maybe that would help you to find the issue...

```
[PUSHER DEBUG] Ping sent
2018-03-23 23:13:42:020 Debug[59401:8207170] 🌍 connected -> disconnected
2018-03-23 23:13:42.020491+0300 Debug[59401:8214777] 🌍 connected -> disconnected
2018-03-23 23:13:42:020 Debug[59401:8207170] RTC connection failed with fatal error
2018-03-23 23:13:42.020586+0300 Debug[59401:8215667] RTC connection failed with fatal error
[PUSHER DE2018-03-23 23:13:42:023 Debug[59401:8207170] 🌍 disconnected -> reconnecting
BUG]2018-03-23 23:13:42.023348+0300 Debug[59401:8214777] 🌍 disconnected -> reconnecting
 Waiting 0.0 seconds before attempting to reconnect (attempt 1 of 12)
2018-03-23 23:13:42:033 Debug[59401:8207170] 🌍 reconnecting -> connecting
2018-03-23 23:13:42.033593+0300 Debug[59401:8214777] 🌍 reconnecting -> connecting
2018-03-23 23:13:43:437 Debug[59401:8207170] 🌍 connecting -> connected
2018-03-23 23:13:43.437593+0300 Debug[59401:8214777] 🌍 connecting -> connected
[PUSHER DEBUG] sendEvent {"event":"pusher:subscribe","data":{"channel":"announcement-test"}}
[PUSHER DEBUG] websocketDidReceiveMessage {"event":"pusher:connection_established","data":"{\"socket_id\":\"735.1353374\",\"activity_timeout\":120}"}
[PUSHER DEBUG] websocketDidReceiveMessage {"event":"pusher_internal:subscription_succeeded","data":"{}","channel":"announcement-test"}
[PUSHER DEBUG] sendEvent {"event":"pusher:subscribe","data":{"auth":"fe9b5290fxxx8e1b5850:237a3a8fd4f1bbxxx6a58a6d13a32c44704a0d92xxxf19debf6e24xxx6b89c42","channel":"private-project-test@5a7a4e252bxxx69722xxxb6c"}}
[PUSHER DEBUG] websocketDidReceiveMessage {"event":"pusher:error","data":{"code":null,"message":"Invalid signature: Expected HMAC SHA256 hex digest of 735.1353374:private-project-test@5a7a4e252bxxx69722xxxb6c, but got 237a3a8fd4f1bbxxx6a58a6d13a32c44704a0d92xxxf19debf6e24xxx6b89c42"}}
```

Please let me know if you need any other information...

**Comment by hamchapman** [comment] 2018-03-24 22:46
Those logs suggest that the connection is reestablished but the subscription to channel `private-project-test@5a7a4e252bxxx69722xxxb6c` fails because of an invalid auth value. 

That could be because the `socketId` is being cached by the client for too long or at least the old `socketId` value is being used to attempt a subscription, only just before the new value is set. I'll take a look at the code and see if I can spot anything like that.

**Comment by hamchapman** [comment] 2018-03-24 22:54
It looks like it was possible for the old `socketId` to still be used upon reconnection for subscriptions to private / presence channels. I've just pushed a fix for this so if you could try that again and let me know if that fixes the invalid auth error then that would be great! Thanks!

**Comment by borulday** [comment] 2018-03-25 19:37
I couldn't try it deeply yet but it looks like it's fixed! 😄 Thank you! 
If I find any other issue, I'll let you know!

**Closed** 2018-04-04 14:50 UTC
Labels: fix-proposed
